# Generated by Django 3.2.8 on 2021-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAllergy', '0004_rename_lowlevelallergy_allergy_allergyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='highLevelAllergy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
